# vim: et ts=2 sts=2 sw=2 tw=80
font:
  # Normal (roman) font face
  normal:
    family: Caskaydia Cove Nerd Font
    # family: Cascadia Code
    # family: SauceCodePro Nerd Font
    style: Regular
  # Bold font face
  bold:
    family: Caskaydia Cove Nerd Font
    style: Bold
  # Point size
  # size: 8
  size: 12.5
  # use_thin_strokes: false

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

# Colors (Solarized Light)
colors:
  # Default colors
  primary:
    # background: '#fdf6e3' # base3
    background: '#ffffff' #base3
    # foreground: '#657b83' # base00
    foreground: '#000000' # base00

  # Cursor colors
  cursor:
    text:   '#fdf6e3' # base3
    cursor: '#657b83' # base00

  # Normal colors
  normal:
    black:   '#000000' # base02
    red:     '#af0000' # red
    green:   '#008700' # green
    yellow:  '#af5f00' # yellow
    blue:    '#005faf' # blue
    magenta: '#870087' # magenta
    cyan:    '#008787' # cyan
    white:   '#bfbfbf' # base2

  # Bright colors
  bright:
    black:   '#4e4e4e' # base03
    red:     '#af0000' # orange
    green:   '#008700' # base01
    yellow:  '#af5f00' # base00
    blue:    '#005faf' # base0
    magenta: '#870087' # violet
    cyan:    '#008787' # base1
    white:   '#cccccc' # base3

